sudo: false
language: ruby
rvm:
- 2.3.1
before_script:
- mysql -e 'create database ifta_conference_test'
- RAILS_ENV=test bundle exec rake db:schema:load
env:
  global:
  - APP_CERT='abc'
  - APP_KEY='abc'
  - SECRET_TOKEN='3d528738744c3e704d619e4ff37117c8'
  - RECAPTCHA_PUBLIC_KEY='6LdFod0SAAAAAFI1MtM_C2MzS0f9KtXSxJYQO29q'
  - secure: "byAfWqfFPiYqkipO/nYHysTxvo2sl0xadpaQWWJ0ByghUFq9n0Ih7kBDpiZ9xfuYQzblcBpET5tHwRa+HTp8XeCzlnCXpc802TTKrrUORhtu8gzb1+zY4b3SyoHRvdKJ36l2ACA3SauIyAfiQNAC1TJ+NRKJ+KkLjDpBKqpPEbI="
  - SUPER_ADMIN_EMAIL='jdoe@example.com'
  - SUPER_ADMIN_PASSWORD='12345'
  - GMAIL_DOMAIN='augustana.edu'
  - GMAIL_USERNAME='jdoe@example.com'
  - GMAIL_PASSWORD='12345'
  - MAILER_HOST='localhost:3000'
  - PAYPAL_POST_URL='https://www.sandbox.paypal.com/cgi-bin/webscr'
  - PAYPAL_NOTIFY_URL='http://guilddev.augustana.edu/payments/'
  - PAYPAL_RETURN_URL='http://guilddev.augustana.edu/itineraries/'
  - PAYPAL_SELLER='seller_1358613005_biz@gmail.com'
  - PAYPAL_CERT_ID='PM7ZU9P7KX3JQ'
  - PAYPAL_CERT_PEM='paypal_sandbox_cert.pem'
  - MYSQL_USERNAME='root'
  - MYSQL_PASSWORD=''
  - SECRET_KEY_BASE=12345
  - DEVISE_SECRET=67890
deploy:
  provider: heroku
  api_key:
    secure: "CQ3eyHp+xYxw0GTHTGb+am33sTd0jSk5CQD5FIKEKrxkFQWCldQxyCT5c1hp+PuV/UEK0UbOBBJJqgeHhCdYempi+icppU9dsAHWkHf1vHingrg3Njg9DRpxk82mp/JlIasIX/OvXJRFkovnFp6JhlHXrO5tHdqE4B4ZTeYuq7c="
  app:
    staging: 'ifta-stage'
    master: 'ifta'
