version: '2'

services:
  db:
    image: 'mysql:5.5.62'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  web:
    tty: true
    image: 'bitnami/rails:6-debian-10'
    labels:
      kompose.service.type: nodeport
    environment:
      - DATABASE_URL=mysql2://db/ifta_development
      - DEVISE_SECRET=12845023948304
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD
      - SECRET_KEY_BASE=123424423
      - SECRET_TOKEN=30432493285
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ifta-gems:/usr/local/bundle
volumes:
  db:
    driver: local
  ifta-gems:
    driver: local
