version: '2'

services:
  db:
    image: 'mariadb:11.1.3-jammy'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  web:
    entrypoint: /app/docker-entrypoint.sh
    tty: true
    image: 'ruby:3.2.2-bullseye'
    labels:
      kompose.service.type: nodeport
    environment:
      - DATABASE_URL=mysql2://db/ifta_development
      - DEVISE_SECRET=12845023948304
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD
      - SECRET_KEY_BASE=123424423
      - SECRET_TOKEN=30432493285
      - BUNDLER_VERSION=2.4.10
      - RAILS_ENV=development
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ifta-gems:/usr/local/bundle
volumes:
  db:
    driver: local
  ifta-gems:
    driver: local
