source 'https://rubygems.org'
ruby '2.1.2'

gem 'rails', '4.2.3'

gem 'activerecord-import'
gem 'angularjs-rails'
gem 'cancan'
gem 'coffee-rails'
gem 'delayed_job_active_record'
gem 'devise'
gem 'foreman'
gem 'gon'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'mysql2', '~> 0.3.20'
gem 'newrelic_rpm'
gem 'oj'
gem 'paper_trail'
gem 'rabl'
gem 'recaptcha', :require => 'recaptcha/rails'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'underscore-rails'
gem 'validates_existence'
gem 'validates_timeliness'
gem 'will_paginate'

group :production do
  gem 'therubyracer', :platform => :ruby
end

group :development, :test do
  gem 'awesome_print'
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'meta_request'
  gem 'mocha'
  gem 'poltergeist'
  gem 'quiet_assets'
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'spork'
  gem 'rspec-core'
  gem 'rspec-rails'
  gem 'thin'
end
