secret_token: ''
recaptcha_public_key: ''
recaptcha_private_key: ''
super_admin_email: ''
super_admin_password: ''
  
development:
  gmail_domain: ''
  gmail_username: ''
  gmail_password: ''
  mailer_host: ''
  paypal_post_url: 'https://www.sandbox.paypal.com/cgi-bin/webscr'
  paypal_notify_url: 'http://guilddev.augustana.edu/payments/'
  paypal_return_url: 'http://guilddev.augustana.edu/itineraries/'
  paypal_seller: ''
  paypal_cert_id: ''
  
 
production:
  gmail_domain: ''
  gmail_username: ''
  gmail_password: ''
  mailer_host: ''
  paypal_post_url: 'https://www.paypal.com/cgi-bin/webscr'
  paypal_notify_url: 'http://www.ifta2014.org/payments/'
  paypal_return_url: 'http://www.ifta2014.org/itineraries/'
  paypal_seller: ''
  paypal_cert_id: ''
  mysql_username: ''
  mysql_password: ''