secret_token: <%= ENV["SECRET_TOKEN"] %>
recaptcha_public_key: <%= ENV["RECAPTCHA_PUBLIC_KEY"] %>
recaptcha_private_key: <%= ENV["RECAPTCHA_PRIVATE_KEY"] %>
super_admin_email: <%= ENV["SUPER_ADMIN_EMAIL"] %>
super_admin_password: <%= ENV["SUPER_ADMIN_PASSWORD"] %>
gmail_domain: <%= ENV["GMAIL_DOMAIN"] %>
gmail_username: <%= ENV["GMAIL_USERNAME"] %>
gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
mailer_host: <%= ENV["MAILER_HOST"] %>
paypal_post_url: <%= ENV["PAYPAL_POST_URL"] %>
paypal_notify_url: <%= ENV["PAYPAL_NOTIFY_URL"] %>
paypal_return_url: <%= ENV["PAYPAL_RETURN_URL"] %>
paypal_seller: <%= ENV["PAYPAL_SELLER"] %>
paypal_cert_id: <%= ENV["PAYPAL_CERT_ID"] %>
paypal_cert_pem: <%= ENV["PAYPAL_CERT_PEM"] %>
mysql_username: <%= ENV["MYSQL_USERNAME"] %>
mysql_password: <%= ENV["MYSQL_PASSWORD"] %>
app_cert: <%= ENV["APP_CERT"] %>
app_key: <%= ENV["APP_KEY"] %>