name: Run RSpec

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:11.1.3-jammy
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libmysqlclient-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup test database
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root:password@localhost/test
        run: |
          bundle exec rake db:create && bundle exec rake db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          APP_CERT: abc
          APP_KEY: abc
          SECRET_TOKEN: abc
          RECAPTCHA_PUBLIC_KEY: 6LdFod0SAAAAAFI1MtM_C2MzS0f9KtXSxJYQO29q
          SUPER_ADMIN_EMAIL: jdoe@example.com
          SUPER_ADMIN_PASSWORD: 12345
          GMAIL_DOMAIN: augustana.edu
          GMAIL_USERNAME: jdoe@example.com
          GMAIL_PASSWORD: 12345
          MAILER_HOST: localhost:3000
          PAYPAL_POST_URL: https://www.sandbox.paypal.com/cgi-bin/webscr
          PAYPAL_NOTIFY_URL: http://guilddev.augustana.edu/payments/
          PAYPAL_RETURN_URL: http://guilddev.augustana.edu/itineraries/
          PAYPAL_SELLER: seller_1358613005_biz@gmail.com
          PAYPAL_CERT_ID: PM7ZU9P7KX3JQ
          PAYPAL_CERT_PEM: paypal_sandbox_cert.pem
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: password
          SECRET_KEY_BASE: 12345
          DEVISE_SECRET: 67890
          DATABASE_URL: mysql2://root:password@localhost/test
        run: |
          bundle exec rspec