name: Run RSpec

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:11.1.3-jammy
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libmysqlclient-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup test database
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root:password@localhost/test
        run: |
          bundle exec rake db:create && bundle exec rake db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://root:password@localhost/test
        run: |
          bundle exec rspec